site_name: Wiki
site_url: https://bahamut731lp.github.io/wiki
dev_addr: "0.0.0.0:8000"

plugins:
  - search
  - blog:
      blog_toc: true
      authors_profiles: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - tables
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true

nav:
  - Domů: index.md
  - Kombinatorika:
      - kombinatorika/index.md
      - kombinatorika/kombinatoricka_pravidla.md
  - Statistika:
      - statistika/index.md
      - statistika/teorie_pravdepodobnosti/jevy.md
      - statistika/teorie_pravdepodobnosti/pravdepodobnost.md
  - Lineární algebra:
      - linearni_algebra/index.md
      - linearni_algebra\linearni_kombinace.md
      - linearni_algebra\matice.md
      - linearni_algebra\vektorove_prostory.md
      - linearni_algebra\vlastni_cisla_vektory.md
  - Blog:
      - blog/index.md

theme:
  name: material
  language: cs
  custom_dir: overrides
  features:
    - header.autohide
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - announce.dismiss
  palette:
    scheme: slate
    primary: purple
    accent: blue

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/bahamut731lp

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js