site_name: Wiki
dev_addr: "0.0.0.0:8000"

site_url: https://bahamut731lp.github.io/wiki
repo_url: https://github.com/bahamut731lp/wiki
edit_uri: edit/main/docs/

plugins:
  - search
  - blog:
      blog_toc: true
      authors_profiles: true
  - git-authors

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - tables
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true

nav:
  - Domů: index.md
  - Algoritmy a programování:
    - algoritmy_a_programovani/index.md
    - algoritmy_a_programovani/ciselne_soustavy.md
    - algoritmy_a_programovani/algoritmizace.md
    - algoritmy_a_programovani/slozitost.md
    - algoritmy_a_programovani/vyhledavani_razeni.md
    - algoritmy_a_programovani/rekurze.md
    - algoritmy_a_programovani/cleneni_programu.md
  - Databázové systémy:
    - databazove_systemy/index.md
    - Relační:
      - databazove_systemy/relacni/navrh.md
      - databazove_systemy/relacni/funkcni_zavislost.md
      - databazove_systemy/relacni/normalizace.md
      - databazove_systemy/relacni/aktualizacni_anomalie.md

  - Hardware a elektronika:
    - logicke_obvody/prevodniky.md
    - logicke_obvody/kombinacni_logicke_obvody.md
    - logicke_obvody/sekvencni_logicke_obvody.md
    - logicke_obvody/aritmeticke_obvody.md
    - logicke_obvody/automaty.md
    - logicke_obvody/procesory.md
  - Matematika:
    - Kombinatorika:
      - kombinatorika/index.md
      - kombinatorika/kombinatoricka_pravidla.md
    - Statistika:
      - statistika/index.md
      - statistika/teorie_pravdepodobnosti/jevy.md
      - statistika/teorie_pravdepodobnosti/pravdepodobnost.md
      - statistika/teorie_pravdepodobnosti/podminena_pravdepodobnost.md
      - statistika/teorie_pravdepodobnosti/nahodna_velicina.md
      - statistika/teorie_pravdepodobnosti/ciselne_charakteristiky.md
    - Lineární algebra:
      - linearni_algebra/index.md
      - linearni_algebra/linearni_kombinace.md
      - linearni_algebra/matice.md
      - linearni_algebra/vektorove_prostory.md
      - linearni_algebra/vlastni_cisla_vektory.md
    - Reálná analýza:
      - realna_analyza/derivace.md
      - realna_analyza/diferencial.md
      - realna_analyza/integral.md
  - Signály a informace:
    - signaly_a_informace/index.md
    - signaly_a_informace/signaly.md
    - signaly_a_informace/ad_prevod.md
    - signaly_a_informace/systemy.md
    - signaly_a_informace/konvoluce.md
    - signaly_a_informace/fourierovy_rady.md
    - signaly_a_informace/spektrum.md
    - signaly_a_informace/filtry.md
  - Operační systémy:
    - operacni_systemy/index.md
    - operacni_systemy/procesy.md
  - Blog:
    - blog/index.md

theme:
  name: material
  language: cs
  custom_dir: overrides
  features:
    - header.autohide
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - announce.dismiss
    - content.action.edit
  palette:
    scheme: slate
    primary: purple
    accent: blue
  icon:
    edit: material/pencil 
    view: material/eye

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/bahamut731lp

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js