site_name: Wiki
dev_addr: "0.0.0.0:8000"

site_url: https://bahamut731lp.github.io/wiki
repo_url: https://github.com/bahamut731lp/wiki
edit_uri: edit/main/docs/

plugins:
  - search
  - blog:
      blog_toc: true
      authors_profiles: true
  - git-authors

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - tables
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true

nav:
  - Domů: index.md
  - Algoritmy a programování:
    - algoritmy_a_programovani/index.md
    - algoritmy_a_programovani/algoritmizace.md
    - algoritmy_a_programovani/slozitost.md
    - algoritmy_a_programovani/vyhledavani_razeni.md
    - algoritmy_a_programovani/rekurze.md
    - algoritmy_a_programovani/cleneni_programu.md
  - Databázové systémy:
    - databazove_systemy/index.md
    - Relační:
      - databazove_systemy/relacni/navrh.md
      - databazove_systemy/relacni/funkcni_zavislost.md
      - databazove_systemy/relacni/normalizace.md
      - databazove_systemy/relacni/aktualizacni_anomalie.md

  - Gramatiky a automaty:
    - gramatiky_automaty/index.md
    - gramatiky_automaty/abecedy_slova.md
    - gramatiky_automaty/formalni_jazyky.md
    - gramatiky_automaty/automaty.md
    - gramatiky_automaty/gramatiky.md
  - Hardware a elektronika:
    - logicke_obvody/ciselne_soustavy.md
    - logicke_obvody/prevodniky.md
    - logicke_obvody/kombinacni_logicke_obvody.md
    - logicke_obvody/sekvencni_logicke_obvody.md
    - logicke_obvody/aritmeticke_obvody.md
    - logicke_obvody/automaty.md
    - logicke_obvody/procesory.md
  - Matematika:
    - Reálná analýza:
      - Funkce:
        - matematika/funkce/index.md
        - matematika/funkce/inverzni.md
    - Analytická geometrie:
      - analyticka_geometrie/vektory.md
      - analyticka_geometrie/parametricka_primka.md
      - analyticka_geometrie/obecna_primka.md
      - analyticka_geometrie/uhel_mezi_primkami.md
    - Diskrétní matematika:
      - matematika/diskretni_matematika/index.md
      - Algebraické struktury:
        - matematika/diskretni_matematika/algebraicke_struktury/polynomy.md
        - matematika/diskretni_matematika/algebraicke_struktury/permutace.md
      - Teorie dělitelnosti:
        - matematika/diskretni_matematika/teorie_delitelnosti/index.md
        - matematika/diskretni_matematika/teorie_delitelnosti/delitelnost.md
        - matematika/diskretni_matematika/teorie_delitelnosti/spolecny_delitel.md
        - matematika/diskretni_matematika/teorie_delitelnosti/prvocisla.md
        - matematika/diskretni_matematika/teorie_delitelnosti/spolecny_nasobek.md
        - matematika/diskretni_matematika/teorie_delitelnosti/bezoutova_rovnost.md
        - matematika/diskretni_matematika/teorie_delitelnosti/mobiova_funkce.md
        - matematika/diskretni_matematika/teorie_delitelnosti/eulerova_funkce.md
        - matematika/diskretni_matematika/teorie_delitelnosti/dolni_horni_cela_cast.md
        - matematika/diskretni_matematika/teorie_delitelnosti/retezove_zlomky.md
        - matematika/diskretni_matematika/teorie_delitelnosti/kongruence.md

    - Statistika:
      - matematika/statistika/index.md
      - matematika/statistika/teorie_pravdepodobnosti/jevy.md
      - matematika/statistika/teorie_pravdepodobnosti/pravdepodobnost.md
      - matematika/statistika/teorie_pravdepodobnosti/podminena_pravdepodobnost.md
      - matematika/statistika/teorie_pravdepodobnosti/nahodna_velicina.md
      - matematika/statistika/teorie_pravdepodobnosti/ciselne_charakteristiky.md
      - Rozdělení pravděpodobnosti:
        - matematika/statistika/rozdeleni/hypergeometricke.md
        - matematika/statistika/rozdeleni/binomicke.md
        - matematika/statistika/rozdeleni/poissonovo.md
        - matematika/statistika/rozdeleni/alternativni.md
        - matematika/statistika/rozdeleni/geometricke.md
        - matematika/statistika/rozdeleni/multinomicke.md
    - Kombinatorika:
      - matematika/kombinatorika/index.md
      - matematika/kombinatorika/kombinatoricka_pravidla.md
    - Reálná analýza:
      - realna_analyza/derivace.md
      - realna_analyza/diferencial.md
      - realna_analyza/integral.md
    - Zjednodušování výrazů:
      - matematika/zlomky.md
      - matematika/exponenty.md
      - matematika/logaritmy.md
  - Signály a informace:
    - signaly_a_informace/index.md
    - signaly_a_informace/signaly.md
    - signaly_a_informace/ad_prevod.md
    - signaly_a_informace/systemy.md
    - signaly_a_informace/konvoluce.md
    - signaly_a_informace/fourierovy_rady.md
    - signaly_a_informace/spektrum.md
    - signaly_a_informace/filtry.md
  - Operační systémy:
    - operacni_systemy/index.md
    - operacni_systemy/procesy.md
  - Blog:
    - blog/index.md

theme:
  name: material
  language: cs
  custom_dir: overrides
  features:
    - header.autohide
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - announce.dismiss
    - content.action.edit
  palette:
    scheme: slate
    primary: purple
    accent: blue
  icon:
    edit: material/pencil 
    view: material/eye

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/bahamut731lp

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js